 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alan.valler
 */
public class Lanchonete_V2 extends javax.swing.JFrame {

    /**
     * Creates new form Lanchonete
     */
    public Lanchonete_V2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        txtBV = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPao = new javax.swing.JLabel();
        cbPao = new javax.swing.JComboBox<>();
        txtMolho = new javax.swing.JLabel();
        cbMolho = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        txtHamburg = new javax.swing.JLabel();
        slHamburg = new javax.swing.JSlider();
        txtQueijo = new javax.swing.JLabel();
        cbQueijo = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        txtSalad = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        txtTaxaServ = new javax.swing.JLabel();
        txtTaxa = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnPedido = new javax.swing.JButton();
        txtLista = new javax.swing.JLabel();
        txtTaxaResult = new javax.swing.JLabel();
        lblSelec01 = new javax.swing.JLabel();
        txtPaoResult = new javax.swing.JLabel();
        lblSelec02 = new javax.swing.JLabel();
        txtMolhoResult = new javax.swing.JLabel();
        lblSelec03 = new javax.swing.JLabel();
        txtHamburgResult = new javax.swing.JLabel();
        lblSelec05 = new javax.swing.JLabel();
        txtQueijoResult = new javax.swing.JLabel();
        lblSelec04 = new javax.swing.JLabel();
        txtSaladResult = new javax.swing.JLabel();
        lblSelec06 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lblResultado = new javax.swing.JLabel();
        txtResultadoFinal = new javax.swing.JTextField();
        cbSalada = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LANCHE-NET");

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTitulo.setText("LANCHE-NET");
        txtTitulo.setToolTipText("");

        txtBV.setText("Bem Vindo (a)");

        txtPao.setText("TIPO DE PÃO");

        cbPao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brioche (R$5.00)", "Australiano (R$7.50)", "Italiano (R$7.50)", "Sem Glúten (R$5.00)" }));
        cbPao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaoActionPerformed(evt);
            }
        });

        txtMolho.setText("TIPOS DE MOLHOS");

        cbMolho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum (R$0.00)", "Maionese (R$1.00)", "Ketchup (R$1.00)", "Barbecue (R$1.00)", "Mostarda (R$1.00)", "Mostarda e Mel (R$1.50)", "Parmesão (R$1.50)", "Cebola Agridoce (R$1.50)" }));

        txtHamburg.setText("QTD. DE HAMBÚRGUERES");

        slHamburg.setMajorTickSpacing(1);
        slHamburg.setMaximum(5);
        slHamburg.setPaintLabels(true);
        slHamburg.setPaintTicks(true);
        slHamburg.setSnapToTicks(true);

        txtQueijo.setText("TIPO DE QUEIJO");

        cbQueijo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum (R$0.00)", "Cheddar (R$5.00)", "Prato (R$3.50)", "Suíço (R$4.00)", "DobroCheddar (R$9.00)", "Dobro Prato (R$6.00)" }));

        txtSalad.setText("SALADAS/VEGETAIS");

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtTaxaServ.setText("TAXA DE SERVIÇO:");

        txtTaxa.setText("R$10,00");

        btnPedido.setText("FAZER PEDIDO");
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });

        txtLista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLista.setText("LISTA");

        txtTaxaResult.setText("TAXA:");

        lblSelec01.setText("R$10,00");

        txtPaoResult.setText("TIPO DE PÃO:");

        lblSelec02.setText("SELEC.");

        txtMolhoResult.setText("TIPO DE MOLHOS:");

        lblSelec03.setText("SELEC.");

        txtHamburgResult.setText("QTD. DE HAMB.");

        lblSelec05.setText("SELEC.");

        txtQueijoResult.setText("TIPO DE QUEIJO:");

        lblSelec04.setText("SELEC.");

        txtSaladResult.setText("SALD/VEG:");

        lblSelec06.setText("SELEC.");

        lblResultado.setText("RESULTADO");

        txtResultadoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoFinalActionPerformed(evt);
            }
        });

        cbSalada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum (R$0.00)", "Alface (R$1.00)", "Tomate (R$1.00)", "Pepino (R$1.00)", "Pimentão (R$1.00)", "Cebola (R$1.00)", "Azeitona (R$1.00)" }));
        cbSalada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSaladaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBV)
                            .addComponent(txtTitulo)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtSalad)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(slHamburg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbQueijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtPao)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMolho)
                                    .addGap(42, 42, 42))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbPao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbMolho, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtHamburg)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtQueijo)
                                    .addGap(30, 30, 30)))
                            .addComponent(cbSalada, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSaladResult)
                            .addComponent(txtQueijoResult)
                            .addComponent(txtHamburgResult)
                            .addComponent(txtMolhoResult)
                            .addComponent(txtTaxaResult)
                            .addComponent(txtPaoResult))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSelec03)
                            .addComponent(lblSelec02)
                            .addComponent(lblSelec06)
                            .addComponent(lblSelec05)
                            .addComponent(lblSelec04)
                            .addComponent(lblSelec01)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtTaxaServ)
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtTaxa)
                                .addGap(86, 86, 86))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtResultadoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPedido)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblResultado)
                            .addComponent(txtLista))
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtTitulo)
                        .addGap(3, 3, 3)
                        .addComponent(txtBV)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPao)
                                            .addComponent(txtMolho))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbPao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbMolho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(11, 11, 11)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtHamburg)
                                            .addComponent(txtQueijo))
                                        .addGap(12, 12, 12)
                                        .addComponent(slHamburg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbQueijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSalad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbSalada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLista, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTaxaResult)
                                    .addComponent(lblSelec01))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPaoResult)
                                    .addComponent(lblSelec02))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSelec03)
                                    .addComponent(txtMolhoResult))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHamburgResult)
                                    .addComponent(lblSelec04))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtQueijoResult)
                                    .addComponent(lblSelec05))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSaladResult)
                                    .addComponent(lblSelec06))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblResultado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(txtResultadoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(txtTaxaServ, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTaxa))
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    float Valor =10;
    private void cbPaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbPaoActionPerformed

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        // TODO add your handling code here:
        lblSelec02.setText(""+cbPao.getSelectedItem());
            if (cbPao.getSelectedItem().equals("Brioche (R$5.00)")||cbPao.getSelectedItem().equals("Sem Glúten (R$5.00)")){
            Valor += 5;
            } 
            else {
            Valor += 7.5;
            }
        
        lblSelec03.setText (""+cbMolho.getSelectedItem());
            if (cbMolho.getSelectedItem().equals("Cebola Agridoce (R$1.50)")|| cbMolho.getSelectedItem().equals("Mostarda e Mel (R$1.50)")||cbMolho.getSelectedItem().equals("Parmesão (R$1.50)")){
            Valor += 1.5;
            }
            else if(cbMolho.getSelectedItem().equals("Nenhum (R$0.00)")){
            Valor += 0;
            }
            else {
            Valor +=1;
            }
            
            
            int quantidade=0;
            quantidade = slHamburg.getValue();
            Valor=Valor+(quantidade*5);
            lblSelec04.setText(""+quantidade);
        
        lblSelec05.setText (""+cbQueijo.getSelectedItem());
            if (cbQueijo.getSelectedItem().equals ("Prato (R$3.50)")){
            Valor += 3.5;
            }
            else if (cbQueijo.getSelectedItem().equals ("Suíço (R$4.00)")){
            Valor += 4;
            }
            else if (cbQueijo.getSelectedItem().equals ("Cheddar (R$5.00)")){
            Valor += 5;
            }
            else if (cbQueijo.getSelectedItem().equals ("Dobro Prato (R$6.00)")){
            Valor += 6;
            }
            else if (cbQueijo.getSelectedItem().equals ("DobroCheddar (R$9.00)")){
            Valor += 9;
            }
            else {
            Valor +=0;
            };
        
        lblSelec06.setText(""+cbSalada.getSelectedItem());
            if (cbSalada.getSelectedItem().equals("Nenhum (R$0.00)")){
            Valor += 0;
            } 
            else {
            Valor += 1;
            }
        
        txtResultadoFinal.setText("R$"+Valor);
        
        
        
    }//GEN-LAST:event_btnPedidoActionPerformed

    private void txtResultadoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoFinalActionPerformed

    private void cbSaladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSaladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSaladaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lanchonete_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lanchonete_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lanchonete_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lanchonete_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lanchonete_V2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPedido;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cbMolho;
    private javax.swing.JComboBox<String> cbPao;
    private javax.swing.JComboBox<String> cbQueijo;
    private javax.swing.JComboBox<String> cbSalada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblSelec01;
    private javax.swing.JLabel lblSelec02;
    private javax.swing.JLabel lblSelec03;
    private javax.swing.JLabel lblSelec04;
    private javax.swing.JLabel lblSelec05;
    private javax.swing.JLabel lblSelec06;
    private javax.swing.JSlider slHamburg;
    private javax.swing.JLabel txtBV;
    private javax.swing.JLabel txtHamburg;
    private javax.swing.JLabel txtHamburgResult;
    private javax.swing.JLabel txtLista;
    private javax.swing.JLabel txtMolho;
    private javax.swing.JLabel txtMolhoResult;
    private javax.swing.JLabel txtPao;
    private javax.swing.JLabel txtPaoResult;
    private javax.swing.JLabel txtQueijo;
    private javax.swing.JLabel txtQueijoResult;
    private javax.swing.JTextField txtResultadoFinal;
    private javax.swing.JLabel txtSalad;
    private javax.swing.JLabel txtSaladResult;
    private javax.swing.JLabel txtTaxa;
    private javax.swing.JLabel txtTaxaResult;
    private javax.swing.JLabel txtTaxaServ;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
